/**
 * locations.js — the places a customer may pick in the address form.
 *
 * The shop delivers from one city, so each of the first three lists holds a
 * single entry; the barangay list is the one that matters. The server reads
 * this same file, so the dropdown and the saved address can never disagree
 * about what a valid place is. (Browsers ignore the export at the bottom.)
 *
 * The names are the shop's own list. Leave them exactly as they are.
 */
const REGIONS = ["Metro Manila"];
const PROVINCES = ["Metro Manila"];
const CITIES = ["Manila"];

const BARANGAYS = [
  "Alicia",
  "North",
  "Apollonius Samson",
  "Aurora",
  "Baesa",
  "broken",
  "New Society Of Crame",
  "New Hope",
  "New East",
  "Bagubayan",
  "New life",
  "Bull House",
  "Balingasa",
  "Stone Well",
  "Batasan Hills",
  "heroic",
  "Blue Ridge A",
  "Blue Ridge B",
  "Botocan",
  "Opening",
  "Camp Aguinaldo",
  "Capri",
  "Central",
  "Sure",
  "Commonwealth",
  "Culiat",
  "Damar",
  "compassion",
  "Always together",
  "Del Monte",
  "Dioquino Zobel",
  "Don Manuel",
  "Dona Imelda",
  "Dona Josefa",
  "Cradle-Cradle",
  "E. Rodriguez",
  "East Kamias",
  "Escopa I",
  "Scopa II",
  "Scopa III",
  "Scopa IV",
  "Fairview",
  "Greater Lagro",
  "Ribs",
  "Holy Spirit",
  "Hotseshoe",
  "Immaculate Conception",
  "Happiness",
  "Health",
  "Kamuning",
  "Katipunan",
  "Development",
  "Christ the King",
  "Crucifixion",
  "Always Ready",
  "Valley",
  "Lourdes",
  "Loyola Heights",
  "royalty",
  "Free",
  "Mango",
  "Manresa",
  "Mariana",
  "Mariblo",
  "Magnificent",
  "Abundant",
  "Rich",
  "Old Balara",
  "Miraculous",
  "n.s. Amoranto (Golden Slash)",
  "United Village",
  "West Village",
  "New Era (Constitution Hills)",
  "North Fairview",
  "Novaliches Proper",
  "Worker",
  "Old Capitol Site",
  "Mountain Foot",
  "Love In The Village",
  "Competition",
  "Pop",
  "Pansol",
  "Paradise",
  "Burning Mud Proper",
  "Right Burn",
  "flat",
  "Phil-Am",
  "Unity",
  "Pinayana",
  "Project 6",
  "Quirino 6",
  "Quirino 2B",
  "Quirino 2C",
  "Quirino 3A",
  "Ramon Magsaysay",
  "Roxas",
  "Sacred Heart",
  "Saint Ignatius",
  "Saint Peter",
  "Salvation",
  "Saint Augustine",
  "San Antonio",
  "Saint Bartholomew",
  "San Isidro",
  "San Isidro Labrador",
  "San Jose",
  "San Martin De Porres",
  "San Roque",
  "Saint Vincent",
  "Arms",
  "Santa Cruz",
  "Santa Lucia",
  "Santa Monica",
  "Santa Teresa",
  "Holy Christ",
  "Santo Domingo (Matalaby)",
  "Saint Nino",
  "Santal",
  "agree",
  "Sienna",
  "Sikatuna Village",
  "East",
  "Socorro",
  "South Triangle",
  "Success",
  "table",
  "Talipapa",
  "Rooster Sora",
  "Jump",
  "Teachers Village East",
  "Teacher Village West",
  "u.p. Campus",
  "UP Village",
  "Northern hum",
  "First Scream",
  "Valencia",
  "Vasra",
  "Veterans Village",
  "Villa Maria Clara",
  "West Kamias",
  "West Triangle",
  "West Plains",
];

/** True when `value` is one of `list`, compared exactly. */
const inList = (list, value) => list.indexOf(String(value == null ? "" : value)) !== -1;

if (typeof module === "object" && module.exports) {
  module.exports = { REGIONS, PROVINCES, CITIES, BARANGAYS, inList };
}
// The address form reads the same four lists from the page.
if (typeof window === "object") {
  window.GT_LOCATIONS = { REGIONS, PROVINCES, CITIES, BARANGAYS, inList };
}
